version: "3.9"

services:
  19bitbot:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./logs:/app/logs
    networks:
      - 19bitbot-network
    restart:
      always

networks:
  19bitbot-network:
